defaults:
  - default

# Number of views parameter for the multi-view datasets
num_views: 2

sample_specific_scene: False
specific_scene_name_train: "chess_train"
specific_scene_name_test: "chess_train"
transform: 'imgnorm'
sequential_view_mode: False

# 7Scenes default evaluation resolution (640x480 -> 4:3 aspect ratio)
resolution_test_seven_scenes: ${dataset.resolution_options.518_1_33_ar}
resolution_train: ${dataset.resolution_options.518_1_33_ar}

# Test Set
# Each sequence yields hundreds of frames; request 140 multi-view samples (~20 per scene)
train_dataset:
  "+ 3 @ ${dataset.seven_scenes_wai.train.dataset_str}"

test_dataset:
  "+ 3 @ ${dataset.seven_scenes_wai.test.dataset_str}"
