# UniCeption encoder string used for selecting encoder class (python3 -m uniception.models.encoders.list)
encoder_str: "dinov2"
# Name of the encoder
name: "dinov2_large"
# Data normalization type
data_norm_type: "dinov2"
# ViT size
size: "large"
# Registers
with_registers: False
# Flag to indicate whether model class uses torch hub
uses_torch_hub: False
#pretrained_checkpoint_path: "/home/xwh/.cache/torch/hub/checkpoints/dinov2_vitl14_pretrain.pth" # 使用您下载权重的实际绝对路径
# Flag to indicate whether to use gradient checkpointing for encoder
gradient_checkpointing: False
