defaults:
  - machine: aws
  - model: default
  - dataset: default
  - _self_

output_dir: ${hydra:run.dir}
root_data_dir: ${machine.root_data_dir}
mapanything_dataset_metadata_dir: ${machine.mapanything_dataset_metadata_dir}
root_pretrained_checkpoints_dir: ${machine.root_pretrained_checkpoints_dir}
root_experiments_dir: ${machine.root_experiments_dir}
root_uniception_pretrained_checkpoints_dir: ${machine.root_uniception_pretrained_checkpoints_dir}
device: cuda

fusion:
  stored_feature_file: ???
  memory_keep_ratio: 1.0
  memory_efficient_inference: false

loss:
  reprojection_weight: 1.0
  xyz_weight: 0.1
  confidence_weight: 1.0

head:
  type: "film"
  hidden_dim: 256
  in_channels: 768
  token_dim: 768
  checkpoint: "/home/xwh/project/map-anything-experiments/mapanything/memory/ace_dataset/ace_regression/ace-queryonly_task-images_only_head-film_loss-xyz_scale-off_var-match_to_gt_ep24_buf5120000.pt"

seed: 0
# Disable CUDNN Benchmark (Disable for variable resolution & number of view training)
disable_cudnn_benchmark: true
# Batch size for inference (Metrics are computed per multi-view set and averaged, not per batch of multi-view sets)
batch_size: 10
# Use mixed precision for inference
amp: 1
# Floating point type to use for mixed precision
amp_dtype: "bf16"
# 显存优化
memory_efficient_inference: False

